apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-server
  template:
    metadata:
      labels:
        app: echoserver-server
    spec:
      containers:
        - image: ewoutp/docker-nginx-curl
          imagePullPolicy: IfNotPresent
          name: echoserver-server
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
      nodeSelector:
        kubernetes.io/hostname: "ip-172-31-34-147"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-server
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver-server
